### ISSUE TITLE
ParseOpenScenario() expects not mandatory attribute "Event.maximumExecutionCount"

### ISSUE THREAD

**Issue by bleach31** [pyoscx/scenariogeneration#113]
Thank you for great library. 

I found a bug when parsing the scenario.

When parsing an XOSC file, the `scenariogeneration` library expects `<Event maximumExecutionCount="xx"` as a mandatory attribute, but in the XOSC schema this is not mandatory.
This produces an error in `xosc.ParseOpenScenario()` callback.

Example:

```
from scenariogeneration import xosc
a = xosc.ParseOpenScenario("my_scenario.xosc")
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\xosc_reader.py", line 208, in ParseOpenScenario
    return Scenario.parse(loaded_xosc)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\scenario.py", line 151, in parse
    storyboard = StoryBoard.parse(element.find('Storyboard'))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 241, in parse
    storyboard.add_story(Story.parse(s))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 438, in parse
    story.add_act(Act.parse(a))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 569, in parse
    act.add_maneuver_group(ManeuverGroup.parse(m))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 690, in parse
    maneuver_group.add_maneuver(Maneuver.parse(m))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 917, in parse
    man.add_event(Event.parse(e))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\scenariogeneration\xosc\storyboard.py", line 1059, in parse
    maxexec = convert_int(element.attrib['maximumExecutionCount'])
KeyError: 'maximumExecutionCount'
```

If I manually add maximumExecutionCount as follows(right side), The parsing  is successful.

![image](https://user-images.githubusercontent.com/5919566/173997452-3d7d21b9-31c4-448d-8f2c-1cdb9129f449.png)

`maximumExecutionCount` does not appear as mandatory or required in the standard:

here is link to OSC v1.1 spec.

https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.1.1_Model_Documentation/modelDocumentation/index.html

scenariogeneration's versions is 0.7.12

**Comment by mander76** [comment]
Hi

You are correct, it's fixed here: 64ccdeb257c93219db1fa786d0577c977178e905
will be present in the next release.

**Comment by bleach31** [comment]
Thank you for really quick response.

I think 0.8.0 has just been released, Are there any plans for the next release?

**Comment by mander76** [comment]
NOt really, but have some small things already added, so I can make a small release today actually

**Comment by mander76** [comment]
released.

**Comment by bleach31** [comment]
thank you so much!
