### ISSUE TITLE
error parsing acc-test.xosc from esmini

### ISSUE THREAD

**Issue by yonhdee** [pyoscx/scenariogeneration#119]
hi
I wrote a simple test script to learn `scenariogeneration`, and I used the example files from `esmini/resources/xosc`
there's a lot of error messages when I try to parse them

take `acc-test.xosc` for example, I got these
```bash
python3 test.py
Traceback (most recent call last):
  File "/Users/MacBook/workspace/test.py", line 4, in <module>
    xosc = ParseOpenScenario(
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/xosc_reader.py", line 231, in ParseOpenScenario
    return Scenario.parse(loaded_xosc)
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/scenario.py", line 184, in parse
    storyboard = StoryBoard.parse(element.find("Storyboard"))
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/storyboard.py", line 259, in parse
    init = Init.parse(element.find("Init"))
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/storyboard.py", line 99, in parse
    privateaction = _PrivateActionFactory.parse_privateaction(pa)
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/actions.py", line 124, in parse_privateaction
    return ActivateControllerAction.parse(element)
  File "/opt/homebrew/lib/python3.9/site-packages/scenariogeneration/xosc/actions.py", line 2019, in parse
    lateral = convert_bool(aca_element.attrib["lateral"])
AttributeError: 'NoneType' object has no attribute 'attrib'
```

here's my script, I'm using MacBook with M1 chip
```python
from scenariogeneration.xosc.xosc_reader import ParseOpenScenario

if __name__ == "__main__":
    xosc = ParseOpenScenario(
        "/Users/MacBook/workspace/esmini/resources/xosc/acc-test.xosc"
    )
```

**Comment by mander76** [comment]
Hi

Sorry for the late reply (have been on vacation). 
Probably this is due to a missing mandatory field, some scenarios in esmini are missing some of those, will check it out.

**Comment by mander76** [comment]
There was a bug in scenariogeneration
try out this commit e74e529ce1aa19bcedff87ef2ae0a95e9aa0fe90

**Comment by yonhdee** [comment]
thanks very much, `scenariogeneration` is great
